esphome:
  name: haier
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 19
  rx_pin: 20

logger:
  level: WARN

climate:
  - platform: haier
    name: Haier AC
